# Generated by Django 4.2 on 2023-05-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=200)),
                ('isbn', models.IntegerField(max_length=13)),
                ('año_ingreso', models.IntegerField(max_length=4)),
                ('año_edicion', models.IntegerField(max_length=4)),
            ],
        ),
    ]
