# Generated by Django 4.2 on 2023-05-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editorial', models.CharField(max_length=20, verbose_name='Editorial')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=20, verbose_name='Género')),
            ],
        ),
        migrations.AddField(
            model_name='autor',
            name='nacionalidad',
            field=models.CharField(default='nacionalidad', max_length=15, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='apellido',
            field=models.CharField(max_length=80, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.CharField(max_length=200, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='año_edicion',
            field=models.IntegerField(verbose_name='Año de edición'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='año_ingreso',
            field=models.IntegerField(verbose_name='Año de ingreso'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='idioma',
            field=models.CharField(default='Español', max_length=10, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.BigIntegerField(verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
