# Generated by Django 4.1.5 on 2023-05-21 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editorial', models.CharField(max_length=20, verbose_name='Editorial')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(default='Género', max_length=20, verbose_name='Género')),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(max_length=20, verbose_name='Idioma')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=80, verbose_name='Apellido')),
                ('mail', models.EmailField(max_length=128, verbose_name='Email')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='libro',
            name='idioma',
        ),
        migrations.AddField(
            model_name='autor',
            name='nacionalidad',
            field=models.CharField(default='nacionalidad', max_length=15, verbose_name='Nacionalidad'),
        ),
        migrations.AddField(
            model_name='libro',
            name='descripcion',
            field=models.CharField(default='Descripcion', max_length=3000, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='apellido',
            field=models.CharField(max_length=80, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sistema_biblioteca.autor'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='año_edicion',
            field=models.IntegerField(verbose_name='Año de edición'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='año_ingreso',
            field=models.IntegerField(verbose_name='Año de ingreso'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.BigIntegerField(verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='libro',
            name='editoriales',
            field=models.ManyToManyField(to='sistema_biblioteca.editorial'),
        ),
        migrations.AddField(
            model_name='libro',
            name='genero',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sistema_biblioteca.genero'),
        ),
        migrations.AddField(
            model_name='libro',
            name='idiomas',
            field=models.ManyToManyField(to='sistema_biblioteca.idioma'),
        ),
    ]
