# Generated by Django 4.2 on 2023-05-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='libro',
            name='idioma',
            field=models.CharField(default='Español', max_length=10),
        ),
        migrations.AlterField(
            model_name='libro',
            name='año_edicion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='libro',
            name='año_ingreso',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.IntegerField(),
        ),
    ]
