# Generated by Django 4.2.1 on 2023-05-22 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_biblioteca', '0002_bibliotecario_editorial_genero_idioma_lector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='idiomas',
        ),
        migrations.DeleteModel(
            name='Idioma',
        ),
    ]
