# Generated by Django 4.2.1 on 2023-05-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_biblioteca', '0003_remove_libro_idiomas_delete_idioma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='editoriales',
        ),
        migrations.AddField(
            model_name='libro',
            name='idiomas',
            field=models.CharField(default='Idioma', max_length=20, verbose_name='Idioma'),
        ),
        migrations.AddField(
            model_name='libro',
            name='editoriales',
            field=models.ManyToManyField(to='sistema_biblioteca.editorial'),
        ),
    ]
