# Generated by Django 4.2.1 on 2023-05-22 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_biblioteca', '0003_bibliotecario_lector_delete_usuario_autor_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='dni',
        ),
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.CharField(verbose_name='ISBN'),
        ),
    ]
