# Generated by Django 4.2.1 on 2023-05-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_biblioteca', '0004_remove_libro_editoriales_libro_idiomas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='descripcion',
            field=models.CharField(default='Resumen del libro', max_length=3000, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='idiomas',
            field=models.CharField(default='Idioma del libro', max_length=20, verbose_name='Idioma'),
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='idiomas',
            new_name='idioma',
        ),
    ]
