# Generated by Django 4.2 on 2023-05-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_biblioteca', '0002_editorial_genero_idioma_usuario_remove_libro_idioma_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliotecario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=80, verbose_name='Apellido')),
                ('dni', models.IntegerField(default=0, verbose_name='Dni')),
                ('legajo', models.IntegerField(verbose_name='Legajo')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=80, verbose_name='Apellido')),
                ('dni', models.IntegerField(default=0, verbose_name='Dni')),
                ('mail', models.EmailField(max_length=128, verbose_name='Email')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='autor',
            name='dni',
            field=models.IntegerField(default=0, verbose_name='Dni'),
        ),
    ]
