# Generated by Django 4.2.1 on 2023-05-23 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_biblioteca', '0005_alter_libro_descripcion_alter_libro_idiomas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='descripcion',
            field=models.TextField(default='Resumen del libro', max_length=3000, verbose_name='Descripcion'),
        ),
    ]
