# Generated by Django 4.2.1 on 2023-06-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_biblioteca', '0008_alter_autor_nacionalidad_prestamo_libro'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='portada',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
