# Generated by Django 4.2.1 on 2023-06-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_biblioteca', '0009_libro_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=models.ImageField(null=True, upload_to='sistema_biblioteca/catalogo/images/', verbose_name='Portada'),
        ),
    ]
