# Generated by Django 4.2 on 2023-06-13 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_biblioteca', '0010_alter_libro_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Portada'),
        ),
    ]
