# Generated by Django 4.2.1 on 2023-06-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_biblioteca', '0011_alter_libro_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='reserva',
            field=models.BooleanField(default=False),
        ),
    ]
