# Generated by Django 4.2.1 on 2023-06-13 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sistema_biblioteca', '0012_libro_reserva'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bibliotecario',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='reserva',
        ),
        migrations.AddField(
            model_name='prestamo_libro',
            name='reserva',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prestamo_libro',
            name='lector',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuario asociado al préstamo'),
        ),
        migrations.DeleteModel(
            name='Lector',
        ),
    ]
