# Generated by Django 4.2 on 2023-06-20 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_biblioteca', '0014_alter_prestamo_libro_fecha_prestamo_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='genero',
            field=models.CharField(max_length=20, verbose_name='Género'),
        ),
    ]
