# Generated by Django 4.2 on 2023-06-20 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_biblioteca', '0015_alter_genero_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo_libro',
            name='fecha_prestamo_fin',
            field=models.DateField(default=datetime.datetime(2023, 7, 20, 2, 30, 52, 909484), verbose_name='Fin del prestamo'),
        ),
        migrations.AlterField(
            model_name='prestamo_libro',
            name='fecha_prestamo_inicio',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Inicio del prestamo'),
        ),
    ]
