# Generated by Django 4.2.2 on 2023-06-21 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_biblioteca', '0016_alter_prestamo_libro_fecha_prestamo_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo_libro',
            name='reserva',
        ),
        migrations.AlterField(
            model_name='prestamo_libro',
            name='fecha_prestamo_fin',
            field=models.DateField(default=datetime.datetime(2023, 7, 21, 16, 11, 28, 704521), verbose_name='Fin del prestamo'),
        ),
    ]
