# Generated by Django 4.2.2 on 2023-06-17 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_legajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.PositiveIntegerField(blank=True, max_length=10, null=True),
        ),
    ]
