# Generated by Django 4.2 on 2023-06-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
